ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5/sensor/csid
obj-$(CONFIG_MSM_CSID) += msm_csid.o
